export const products = [
  {
    id: 1,
    name: "Fresh Bananas",
    price: 2.99,
    category: "Fruits",
    image: "../public/placeholder.jpg?height=200&width=200",
    stock: 50,
  },
  {
    id: 2,
    name: "Organic Apples",
    price: 4.99,
    category: "Fruits",
    image: "../public/placeholder.jpg?height=200&width=200",
    stock: 30,
  },
  {
    id: 3,
    name: "Whole Milk",
    price: 3.49,
    category: "Dairy",
    image: "../public/placeholder.jpg?height=200&width=200",
    stock: 25,
  },
  {
    id: 4,
    name: "Greek Yogurt",
    price: 5.99,
    category: "Dairy",
    image: "../public/placeholder.jpg?height=200&width=200",
    stock: 20,
  },
  {
    id: 5,
    name: "Sourdough Bread",
    price: 3.99,
    category: "Bakery",
    image: "../public/placeholder.jpg?height=200&width=200",
    stock: 15,
  },
  {
    id: 6,
    name: "Croissants",
    price: 6.99,
    category: "Bakery",
    image: "../public/placeholder.jpg?height=200&width=200",
    stock: 12,
  },
  {
    id: 7,
    name: "Chicken Breast",
    price: 8.99,
    category: "Meat",
    image: "../public/placeholder.jpg?height=200&width=200",
    stock: 18,
  },
  {
    id: 8,
    name: "Ground Beef",
    price: 7.99,
    category: "Meat",
    image: "../public/placeholder.jpg?height=200&width=200",
    stock: 22,
  },
  {
    id: 9,
    name: "Fresh Spinach",
    price: 2.49,
    category: "Vegetables",
    image: "../public/placeholder.jpg?height=200&width=200",
    stock: 35,
  },
  {
    id: 10,
    name: "Bell Peppers",
    price: 3.99,
    category: "Vegetables",
    image: "../public/placeholder.jpg?height=200&width=200",
    stock: 28,
  },
  { id: 11, name: "Pasta", price: 1.99, category: "Pantry", image: "../public/placeholder.jpg?height=200&width=200", stock: 40 },
  {
    id: 12,
    name: "Olive Oil",
    price: 9.99,
    category: "Pantry",
    image: "../public/placeholder.jpg?height=200&width=200",
    stock: 15,
  },
];

export const categories = ["All", "Fruits", "Vegetables", "Dairy", "Meat", "Bakery", "Pantry"];